CREATE TABLE policy (
    policy_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE premium_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id VARCHAR(50) NOT NULL,
    installment_no INT NOT NULL,
    due_date DATE NOT NULL,
    amount_due DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE payment_attempt (
    attempt_id VARCHAR(50) PRIMARY KEY,
    policy_id VARCHAR(50) NOT NULL,
    installment_no INT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    result VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(50),
    idempotency_key VARCHAR(100) NOT NULL UNIQUE,
    external_transaction_id VARCHAR(100),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    retry_eligible BOOLEAN NOT NULL
);

CREATE TABLE delinquency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id VARCHAR(50) NOT NULL,
    days_past_due INT NOT NULL,
    delinquency_status VARCHAR(30) NOT NULL,
    last_evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE retry_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_attempt_id VARCHAR(50) NOT NULL,
    retry_attempt_id VARCHAR(50),
    retry_count INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL
);